root = "."
testdata_dir = "testdata"
# tmp_dir = "tmp"
tmp_dir = "bin"

# Switched from using a tmp directory to a bin directory for build outputs
# Build command now specifically targets ./cmd/api as the sourceinstead
# instead of the current directory (.)
# The executable is now built as ./bin/main instead of ./tmp/main
# The exclusion list has been updated to ignore the new bin directory instead of tmp
[build]
  args_bin = []
  # bin = "./tmp/main"
  # bin = "./tmp/bin"
  # cmd = "go build -o ./tmp/main ."
  bin = "./bin/main"
  cmd = "go build -o ./bin/main ./cmd/api"
  delay = 1000
  # exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_dir = ["assets", "bin", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
